spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tz_rs
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
  liquibase:
    change-log: classpath:changelog.yml